name: Delete old workflow runs

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ secrets.REPO }}
          retain_days: 1
          keep_minimum_runs: 1
